name: C/C++ CI

on: [push, pull_request, workflow_dispatch]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Format check
        run: .github/format-check.sh

  build:
    needs: [format-check]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        config: [RelWithDebInfo]
        include:
          - os: ubuntu-latest
            cache_path: ~/.ccache
            extra_cmake_args:
            cmake_preset: linux-ninja-clang14

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive


      - name: Set up build environment (ubuntu-latest)
        run: |
          sudo add-apt-repository -y ppa:mhier/libboost-latest
          sudo apt update
          sudo apt -y install ccache libboost-filesystem1.81-dev libboost-program-options1.81-dev libboost-system1.81-dev libgtk-3-dev libsdl2-dev ninja-build lld-11
        if: matrix.os == 'ubuntu-latest'


      - uses: actions/cache@v3
        with:
          path: ${{ matrix.cache_path }}
          key: cache-${{ matrix.os }}-${{ matrix.config }}-${{ github.sha }}
          restore-keys: |
            cache-${{ matrix.os }}-${{ matrix.config }}-

      - name: Set up SDL 2.28.3 (ubuntu-latest)
        run: |
          SDL2VER=2.28.3
          if [[ ! -e ~/.ccache ]]; then
            mkdir ~/.ccache
          fi  
          cd ~/.ccache
          if [[ ! -e SDL2-${SDL2VER} ]]; then
            curl -sLO https://libsdl.org/release/SDL2-${SDL2VER}.tar.gz
            tar -xzf SDL2-${SDL2VER}.tar.gz
            cd SDL2-${SDL2VER}
            ./configure --prefix=/usr/local
            make && cd ../
            rm SDL2-${SDL2VER}.tar.gz
          fi
          sudo make -C SDL2-${SDL2VER} install
        if: matrix.os == 'ubuntu-latest'

      - name: CMake
        run: |
          cmake ${{ matrix.extra_cmake_args }} --preset ${{ matrix.cmake_preset }}
          cmake --build build/${{ matrix.cmake_preset }} --config ${{ matrix.config }}

      - name: CTest
        working-directory: build/${{ matrix.cmake_preset }}
        run: ctest --build-config ${{ matrix.config }} --output-on-failure

      - name: Compute git short sha
        shell: bash
        run: echo "git_short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set Build Variable
        shell: bash
        run: echo "build_variable=$(git rev-list HEAD --count)" >> $GITHUB_ENV
        if: matrix.os == 'ubuntu-latest'

      - name: Bundle OpenSSL shared objects
        id: bundle_openssl
        run: |
            cd build/${{ matrix.cmake_preset }}/bin/${{ matrix.config }}
            cp /usr/lib/x86_64-linux-gnu/libssl.so.3 ./libssl.so.3
            cp /usr/lib/x86_64-linux-gnu/libcrypto.so.3 ./libcrypto.so.3
        if: matrix.os == 'ubuntu-latest'
        
      - uses: actions/upload-artifact@v3
        with:
          name: vita3k-${{ env.git_short_sha }}-${{ matrix.os }}
          # path is set up to be <binary_dir>/bin/<config_type> since that's how multi-config
          # generators work on CMake
          path: build/${{ matrix.cmake_preset }}/bin/${{ matrix.config }}

    outputs:
      BuildTag: ${{ env.build_variable }}

  create-release:
    needs: [build]
    runs-on: "ubuntu-20.04"
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Get Build Variable
        run: echo "Build_Variable=${{ needs.build.outputs.BuildTag }}" >> $GITHUB_ENV

      - name: Upload
        shell: bash
        run: |
          mkdir artifacts/
          files=$(find . -name "*latest")
          for f in $files; do
            if [[ $f == *macos-latest ]]
            then
              cp $(basename $f)/$(basename $f).dmg artifacts/macos-latest.dmg
            else
              echo "Compressing $f"
              (cd $(basename $f) && zip -r ../artifacts/$(basename $f  | cut -d "-" -f 3)-latest.zip *)
            fi
          done
          ls -al artifacts/
          wget -c https://github.com/tcnksm/ghr/releases/download/v0.14.0/ghr_v0.14.0_linux_amd64.tar.gz
          tar xfv ghr_v0.14.0_linux_amd64.tar.gz
          ghr_v0.14.0_linux_amd64/ghr -u Vita3K -r Vita3K -recreate -n 'Automatic CI builds' -b "$(printf "Corresponding commit: ${{ github.sha }}\nVita3K Build: ${{ env.Build_Variable }}")" continuous artifacts/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

